name: WakaTime status update 

on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12 am  '0 0 * * *'  
    - cron: '30 19 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          
          BRANCH: "master"
         
          COMMIT_MSG: "Automated Coding Activity Update :fire:"
