name: WakaTime status update 

on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      
      - uses: athul/waka-readme@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          
          BRANCH: "master"
         
          COMMIT_MESSAGE: "Automated Coding Activity Update :star:"

